# Generated by Django 5.2.5 on 2025-11-17 11:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название места')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Город / Место',
                'verbose_name_plural': 'Города / Места',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='Обязательно для входа и уведомлений', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Только +993xxxxxxxx', regex='^\\+993\\d{8}$')], verbose_name='Телефон')),
                ('is_driver', models.BooleanField(default=False, verbose_name='Является водителем')),
                ('is_passenger', models.BooleanField(default=True, verbose_name='Является пассажиром')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, verbose_name='Марка авто')),
                ('model', models.CharField(max_length=100, verbose_name='Модель авто')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет авто')),
                ('car_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{3}[A-Z]{2}$', message='Например: AG123BH')], verbose_name='Гос. номер')),
                ('car_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1995), django.core.validators.MaxValueValidator(2026)], verbose_name='Год выпуска')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг водителя')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='Поездок выполнено')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен админом')),
                ('is_active', models.BooleanField(default=True, verbose_name='На линии')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг пассажира')),
                ('total_rides', models.PositiveIntegerField(default=0, verbose_name='Поездок совершено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200, verbose_name='Имя отправителя')),
                ('sender_phone', models.CharField(max_length=17, verbose_name='Телефон отправителя')),
                ('receiver_name', models.CharField(blank=True, max_length=200, verbose_name='Имя получателя')),
                ('receiver_phone', models.CharField(blank=True, max_length=17, verbose_name='Телефон получателя')),
                ('description', models.TextField(verbose_name='Что везём')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (TMT)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads_from', to='app.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads_to', to='app.place')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_from', to='app.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_to', to='app.place')),
            ],
            options={
                'verbose_name': 'Уведомление водителю',
                'verbose_name_plural': 'Уведомления водителям',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Ugur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('driver', 'Водитель предлагает места'), ('passenger', 'Пассажир ищет поездку')], db_index=True, default='driver', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_ugurs', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugurs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поездка (Ugur)',
                'verbose_name_plural': 'Поездки (Ugur)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UgurRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Время отправления')),
                ('available_seats', models.PositiveSmallIntegerField(default=4, verbose_name='Свободных мест')),
                ('price_per_seat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за место (TMT)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('stops', models.JSONField(blank=True, default=list, verbose_name='Промежуточные остановки')),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='app.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='app.place')),
                ('ugur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='app.ugur')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Отзыв')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('to_user', 'from_user', 'created')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.PositiveSmallIntegerField(default=1, verbose_name='Мест')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.ugurroute')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'unique_together': {('route', 'passenger')},
            },
        ),
    ]
