# Generated by Django 5.2.9 on 2026-01-15 04:49

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ýeriň ady')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Şäher / Ýer',
                'verbose_name_plural': 'Şäherler / Ýerler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(help_text='Mysal: +99361234567', max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+993\\d{8}$')], verbose_name='Telefon belgisi')),
                ('is_driver', models.BooleanField(default=False)),
                ('is_passenger', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Ýeriň ady')),
                ('description', models.TextField(max_length=500, verbose_name='Maglumat')),
                ('latitude', models.CharField(max_length=500, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=500, verbose_name='Longitude')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Häzirki ýeri',
                'verbose_name_plural': 'Bolan ýerleri',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, verbose_name='Ulagyň markasy')),
                ('model', models.CharField(max_length=100, verbose_name='Ulagyň modeli')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Ulagyň reňki')),
                ('car_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{4}[A-Z]{2}$', message='Mysal ucin: AG123BH')], verbose_name='Dowlet belgisi ')),
                ('car_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1995), django.core.validators.MaxValueValidator(2026)], verbose_name='Cykan yyly')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Surujinin reytingi')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='Ýerine ýetiren syýahatlary')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Admin tarapyndan barlanan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ulgamda')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sürüji',
                'verbose_name_plural': 'Sürüjiler',
            },
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Ýolagçynyň reýtingi')),
                ('total_rides', models.PositiveIntegerField(default=0, verbose_name='Syýahat tamamlandy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ýolagçy',
                'verbose_name_plural': 'Ýolagçylar',
            },
        ),
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_from', to='app.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_to', to='app.place')),
            ],
            options={
                'verbose_name': 'Sürüjä bildiriş',
                'verbose_name_plural': 'Sürüjilere bildiriş',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Ugur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('driver', 'Sürüji orun hödürleýär'), ('passenger', 'Ýolagçy orun gözleýär')], db_index=True, default='driver', max_length=20, verbose_name='Görnüşi')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Maglumat')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Döredildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Täzelendi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Işjeň')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandy')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_ugurs', to=settings.AUTH_USER_MODEL, verbose_name='Sürüji')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ugurs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Syýahat (Ugur)',
                'verbose_name_plural': 'Syýahatlar (Ugur)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UgurRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Ugraýan sene')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Ugraýan wagty')),
                ('available_seats', models.PositiveSmallIntegerField(default=4, verbose_name='Boş orun')),
                ('price_per_seat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ýer üçin baha (TMT)')),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='app.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='app.place')),
                ('ugur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='app.ugur')),
            ],
            options={
                'verbose_name': 'Ugur',
                'verbose_name_plural': 'Ugurlar',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Näme alyp gitmeli')),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Agyrlygy (kg)')),
                ('size', models.CharField(blank=True, help_text='Mysal: 50x40x30 sm', max_length=100, verbose_name='Ölçegi')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Kabul edýäniň ady')),
                ('receiver_phone', models.CharField(max_length=17, verbose_name='Kabul edýäniň telefon belgisi')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Baha (TMT)')),
                ('price_negotiable', models.BooleanField(default=True, verbose_name='Baha gepleşiler')),
                ('status', models.CharField(choices=[('searching', 'Sürüji gözlenýär'), ('assigned', 'Sürüji tapylgy'), ('in_transit', 'Ýolda'), ('delivered', 'Gowşuryldy'), ('cancelled', 'Ýatyryldy')], default='searching', max_length=20, verbose_name='Ýagdaýy')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredildi')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Täzelendi')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_loads', to=settings.AUTH_USER_MODEL, verbose_name='Ugradýan')),
                ('ugur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='app.ugur', verbose_name='Baglanan ýol')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='app.ugurroute', verbose_name='Baglanan ugur')),
            ],
            options={
                'verbose_name': 'Ýük (posylka)',
                'verbose_name_plural': 'Ýükler (posylkalar)',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baha')),
                ('comment', models.TextField(blank=True, verbose_name='Bellik')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bellik',
                'verbose_name_plural': 'Bellikler',
                'unique_together': {('to_user', 'from_user', 'created')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.PositiveSmallIntegerField(default=1, verbose_name='Orun')),
                ('status', models.CharField(choices=[('pending', 'Garaşylýar'), ('confirmed', 'Tassyklanan'), ('cancelled', 'Inkär edilen'), ('completed', 'Tamamlandy')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Teswir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.ugurroute')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'unique_together': {('route', 'passenger')},
            },
        ),
    ]
