# Generated by Django 5.2.5 on 2025-11-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterpassenger',
            name='user',
        ),
        migrations.DeleteModel(
            name='FilterDriver',
        ),
        migrations.DeleteModel(
            name='FilterPassenger',
        ),
    ]
