# Generated by Django 5.2.5 on 2025-11-17 12:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivernotification',
            options={'ordering': ['-created'], 'verbose_name': 'Sürüjä bildiriş', 'verbose_name_plural': 'Sürüjilere bildiriş'},
        ),
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'verbose_name': 'Sürüji', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ['-created'], 'verbose_name': 'Ýük (posylka)', 'verbose_name_plural': 'Ýükler (posylkalar)'},
        ),
        migrations.AlterModelOptions(
            name='passengerprofile',
            options={'verbose_name': 'Ýolagçy', 'verbose_name_plural': 'Ýolagçyы'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'Şäher / Ýer', 'verbose_name_plural': 'Şäherler / Ýerler'},
        ),
        migrations.RemoveField(
            model_name='load',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='load',
            name='price_negotiable',
            field=models.BooleanField(default=True, verbose_name='Baha gepleşiler'),
        ),
        migrations.AddField(
            model_name='load',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='app.ugurroute', verbose_name='Baglanan marshrut'),
        ),
        migrations.AddField(
            model_name='load',
            name='sender',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_loads', to=settings.AUTH_USER_MODEL, verbose_name='Ugradýan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='size',
            field=models.CharField(blank=True, help_text='Mysal: 50x40x30 sm', max_length=100, verbose_name='Ölçegi'),
        ),
        migrations.AddField(
            model_name='load',
            name='status',
            field=models.CharField(choices=[('searching', 'Sürüji gözlenýär'), ('assigned', 'Sürüji tapylgy'), ('in_transit', 'Ýolda'), ('delivered', 'Gowşuryldy'), ('cancelled', 'Ýatyryldy')], default='searching', max_length=20, verbose_name='Ýagdaýy'),
        ),
        migrations.AddField(
            model_name='load',
            name='ugur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='app.ugur', verbose_name='Baglanan ýolag'),
        ),
        migrations.AddField(
            model_name='load',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Täzelendi'),
        ),
        migrations.AddField(
            model_name='load',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ağyrlygy (kg)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Teswir'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Orun'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Garaşylýar'), ('confirmed', 'Tassyklanan'), ('cancelled', 'Inkär edilen'), ('completed', 'Tamamlandy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='car_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{4}[A-Z]{2}$', message='Mysal ucin: AG123BH')], verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='load',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Döredildi'),
        ),
        migrations.AlterField(
            model_name='load',
            name='description',
            field=models.TextField(verbose_name='Näme alyp gitmeli'),
        ),
        migrations.AlterField(
            model_name='load',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Baha (TMT)'),
        ),
        migrations.AlterField(
            model_name='load',
            name='receiver_name',
            field=models.CharField(max_length=200, verbose_name='Kabul edýäniň ady'),
        ),
        migrations.AlterField(
            model_name='load',
            name='receiver_phone',
            field=models.CharField(max_length=17, verbose_name='Kabul edýäniň telefon belgisi'),
        ),
        migrations.AlterField(
            model_name='load',
            name='sender_name',
            field=models.CharField(max_length=200, verbose_name='Ugradýanyň ady'),
        ),
        migrations.AlterField(
            model_name='load',
            name='sender_phone',
            field=models.CharField(max_length=17, verbose_name='Ugradýanyň telefon belgisi'),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг Ýolagçyа'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ýeriň ady'),
        ),
        migrations.AlterField(
            model_name='ugur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Döredildi'),
        ),
        migrations.AlterField(
            model_name='ugur',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_ugurs', to=settings.AUTH_USER_MODEL, verbose_name='Sürüji'),
        ),
        migrations.AlterField(
            model_name='ugur',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Işjeň'),
        ),
        migrations.AlterField(
            model_name='ugur',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Tamamlandy'),
        ),
        migrations.AlterField(
            model_name='ugur',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Maglumat'),
        ),
        migrations.AlterField(
            model_name='ugur',
            name='type',
            field=models.CharField(choices=[('driver', 'Sürüji orun hödürleýär'), ('passenger', 'Ýolagçy orun gözleýär')], db_index=True, default='driver', max_length=20, verbose_name='Görnüşi'),
        ),
        migrations.AlterField(
            model_name='ugur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Täzelendi'),
        ),
        migrations.AlterField(
            model_name='ugur',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Görülen'),
        ),
        migrations.AlterField(
            model_name='ugurroute',
            name='available_seats',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Boş orun'),
        ),
        migrations.AlterField(
            model_name='ugurroute',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Teswirler'),
        ),
        migrations.AlterField(
            model_name='ugurroute',
            name='departure_date',
            field=models.DateField(verbose_name='Ugraýan sene'),
        ),
        migrations.AlterField(
            model_name='ugurroute',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ugraýan wagty'),
        ),
        migrations.AlterField(
            model_name='ugurroute',
            name='price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ýer üçin baha (TMT)'),
        ),
        migrations.AlterField(
            model_name='ugurroute',
            name='stops',
            field=models.JSONField(blank=True, default=list, verbose_name='Aralyk duralgalar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_passenger',
            field=models.BooleanField(default=True, verbose_name='Является Ýolagçyом'),
        ),
    ]
