# Generated by Django 5.2.5 on 2025-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_drivernotification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='from_place',
        ),
        migrations.RemoveField(
            model_name='load',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='load',
            name='sender_phone',
        ),
        migrations.RemoveField(
            model_name='load',
            name='to_place',
        ),
        migrations.AlterField(
            model_name='load',
            name='weight_kg',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Agyrlygy (kg)'),
        ),
    ]
