# Generated by Django 5.2.5 on 2025-12-02 04:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_load_from_place_remove_load_sender_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Bron', 'verbose_name_plural': 'Bronlar'},
        ),
        migrations.AlterModelOptions(
            name='passengerprofile',
            options={'verbose_name': 'Ýolagçy', 'verbose_name_plural': 'Ýolagçylar'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Bellik', 'verbose_name_plural': 'Bellikler'},
        ),
        migrations.AlterModelOptions(
            name='ugur',
            options={'ordering': ['-created_at'], 'verbose_name': 'Syýahat (Ugur)', 'verbose_name_plural': 'Syýahatlar (Ugur)'},
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ulagyň reňki'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ulgamda'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Admin tarapyndan barlanan'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='marka',
            field=models.CharField(max_length=100, verbose_name='Ulagyň markasy'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Ulagyň modeli'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='total_trips',
            field=models.PositiveIntegerField(default=0, verbose_name='Ýerine ýetiren syýahatlary'),
        ),
        migrations.AlterField(
            model_name='load',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='app.ugurroute', verbose_name='Baglanan ugur'),
        ),
        migrations.AlterField(
            model_name='load',
            name='ugur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='app.ugur', verbose_name='Baglanan ýol'),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Ýolagçynyň reýtingi'),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='total_rides',
            field=models.PositiveIntegerField(default=0, verbose_name='Syýahat tamamlandy'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Bellik'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Baha'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Sürüji'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_passenger',
            field=models.BooleanField(default=True, verbose_name='Ýolagçy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Giriş we habarnamalar üçin zerur', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Diňe +993xxxxxxxx', regex='^\\+993\\d{8}$')], verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='CurrentPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Ýeriň ady')),
                ('description', models.TextField(max_length=500, verbose_name='Maglumat')),
                ('latitude', models.CharField(max_length=500, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=500, verbose_name='Longitude')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Häzirki ýeri',
                'verbose_name_plural': 'Bolan ýerleri',
            },
        ),
    ]
