# Generated by Django 4.2.9 on 2025-12-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_booking_options_alter_passengerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ugurroute',
            options={'ordering': ['departure_date', 'departure_time'], 'verbose_name': 'Ugur', 'verbose_name_plural': 'Ugurlar'},
        ),
    ]
